name: Release
on:
  release:
    types:
      - published
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  register:
    name: Package, Publish, and Register
    runs-on:
    - ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v3
    - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASS }}
    ## NEW FORTIFY
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download Fortify ScanCentral Client
      uses: fortify/gha-setup-scancentral-client@v1
    - name: Package Code + Dependencies
      run: scancentral package $PACKAGE_OPTS -o package.zip
      env:
        PACKAGE_OPTS: "-bt mvn"
    - name: Download Fortify on Demand Universal CI Tool
      uses: fortify/gha-setup-fod-uploader@v1
    - name: Perform SAST Scan
      run: java -jar target/hola-mundo-0.0.1-SNAPSHOT.jar -z package.zip -aurl $FOD_API_URL -purl $FOD_URL -rid "$FOD_RELEASE_ID" -tc "$FOD_TENANT" -uc "$FOD_USER" "$FOD_PAT" $FOD_UPLOADER_OPTS -n "$FOD_UPLOADER_NOTES"
      env: 
        FOD_TENANT: ${{ secrets.FOD_TENANT }}  
        FOD_USER: ${{ secrets.FOD_USER }}
        FOD_PAT: ${{ secrets.FOD_PAT }}
        FOD_RELEASE_ID: ${{ secrets.FOD_RELEASE_ID }}
        FOD_URL: ${{ secrets.FOD_URL }}
        FOD_API_URL: ${{ secrets.FOD_API_URL }}
        FOD_UPLOADER_OPTS: "-ep 2 -pp 0"
        FOD_UPLOADER_NOTES: 'Triggered by GitHub Actions (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'
    ## END FORTIFY
    - name: Cache Pack
      id: cache-pack
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/pack
        key: ${{ runner.os }}-pack-${{ hashFiles('**/pack*') }}
    - name: cache-ibmcloud
      id: cache-ibmcloud
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/ibmcloud
        key: ${{ runner.os }}-ibmcloud-${{ hashFiles('**/ibmcloud*') }}
    # Configurar paketo https://paketo.io/
    - id: setup-pack
      uses: buildpacks/github-actions/setup-pack@v4.9.0
    - name: build image
      run: pack build ${{ secrets.DOCKER_IMAGE_NAME }} --builder ${{ vars.BUILDER }} --path . 
    - name: Tag Image
      run: docker tag ${{ secrets.DOCKER_IMAGE_NAME }} ${{ secrets.DOCKER_HUB_REPO }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}   
    - name: Push Image
      run: docker push ${{ secrets.DOCKER_HUB_REPO }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}
    # Download and Install IBM Cloud CLI
    - name: Install IBM Cloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f code-engine
        ibmcloud plugin list
    # Authenticate with IBM Cloud CLI
    - name: Authenticate with IBM Cloud CLI
      run: |
        ibmcloud login --apikey "${{ secrets.IBM_USER }}" -r "us-south" -g "${{ secrets.IBM_RESOURCE_GROUP }}"
    - name: Deploy To Code Engine
      run: |
        ibmcloud ce project select --name ${{ secrets.IBM_CE_PROJECT }}
        ibmcloud ce app update  --name ${{ secrets.IBM_CE_APP }} --image  ${{ secrets.DOCKER_HUB_REPO }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}
