name: Release
on:
  release:
    types:
      - published
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  register:
    name: Package, Publish, and Register
    runs-on:
    - ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v3
    - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASS }}
    - name: Cache Pack
      id: cache-pack
      uses: actions/cache@v2
      with:
        path: /usr/local/bin/pack
        key: ${{ runner.os }}-pack-${{ hashFiles('**/pack*') }}
    - id: setup-pack
      uses: buildpacks/github-actions/setup-pack@v4.9.0
    - name: build image
      run: pack build -b paketobuildpacks/builder:base --path . --image hola-mundo
    - id: package
      run: |
        
        docker image ls
        echo  $BUILDER
        echo 
        
      shell: bash
      env:
        REPO: docker.io/${{ secrets.DOCKER_HUB_USER }}
    - id: register
      uses: docker://ghcr.io/buildpacks/actions/registry/request-add-entry:4.9.0
      with:
        token:   ${{ secrets.PUBLIC_REPO_TOKEN }}
        id:      1
        version: ${{ steps.package.outputs.version }}
        address: ${{ steps.package.outputs.address }}
