name: Release
on:
  release:
    types:
      - published
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  register:
    name: Package, Publish, and Register
    runs-on:
    - ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v3
    - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASS }}
    - name: Cache Pack
      id: cache-pack
      uses: actions/cache@v2
      with:
        path: /usr/local/bin/pack
        key: ${{ runner.os }}-pack-${{ hashFiles('**/pack*') }}
    - id: setup-pack
      uses: buildpacks/github-actions/setup-pack@v4.9.0
    - name: build image
      run: pack build hola-mundo --builder paketobuildpacks/builder:base --path . 
    - id: package
      run: |
        
        docker image ls
        
        echo "repository variable : ${{ vars.REPOSITORY_VAR }}"
        echo "organization variable : ${{ vars.ORGANIZATION_VAR }}"
        echo "overridden variable : ${{ vars.OVERRIDE_VAR }}"
        echo "variable from shell environment : $env_var"
        echo Builder ${{ vars.BUILDER }}

        
      shell: bash
      env:
        REPO: docker.io/${{ secrets.DOCKER_HUB_USER }}
    
